apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-deployment-green
  labels:
    app: bg-app
    environment: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bg-app
      environment: green
  template:
    metadata:
      labels:
        app: bg-app
        environment: green
    spec:
      containers:
        - name: bg-app
          image: vani5652/blue-green-demo:green-prod-18
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: green
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
