apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-deployment
  labels:
    app: bg-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bg-app
      environment: blue
  template:
    metadata:
      labels:
        app: bg-app
        environment: blue
    spec:
      containers:
      - name: bg-app
        image: vani5652/blue-green-demo:blue-dev-7
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: blue
          value: "blue"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10

