apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-deployment-DEPLOY_ENV
  labels:
    app: bg-app
    environment: DEPLOY_ENV
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bg-app
      environment: DEPLOY_ENV
  template:
    metadata:
      labels:
        app: bg-app
        environment: DEPLOY_ENV
    spec:
      containers:
        - name: bg-app
          image: IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: DEPLOY_ENV
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
